apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "korean-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwt.secret }}
