apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: korean-learning
  labels:
    app: quiz-service
spec:
  type: ClusterIP
  selector:
    app: quiz-service
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP
