// 韓文字母完整資料庫（含繁體中文解說）
// 資料來源參照：국립국어원 (National Institute of Korean Language)

import { HangulChar } from './types';

export const basicVowels: HangulChar[] = [
  {
    char: 'ㅏ',
    name: '아',
    nameRomanized: 'a',
    romanization: 'a',
    category: 'vowel',
    sound: '/a/',
    zhTW: {
      description: '嘴巴張大，舌頭放平，類似中文「啊」的發音，但嘴型更自然放鬆。韓文的「ㅏ」比中文的「啊」開口稍小。',
      mnemonic: '想像醫生說「啊——」，嘴自然張開。右邊的短豎像舌頭平放。',
      similar: '類似注音「ㄚ」，但嘴型較小',
    },
    strokeOrder: ['M 20,50 L 30,30', 'M 30,50 L 30,30'],
    isBatchim: false,
  },
  {
    char: 'ㅑ',
    name: '야',
    nameRomanized: 'ya',
    romanization: 'ya',
    category: 'vowel',
    sound: '/ja/',
    zhTW: {
      description: '由「ㅣ」(i) +「ㅏ」(a) 組合而成，先發出短促的「ㅣ」再快速滑到「ㅏ」。類似中文「呀」。',
      mnemonic: '比「ㅏ」多了一小橫，就像加上了一個「y」的音。兩橫 = ya。',
      similar: '類似中文「呀」，嘴型由扁到開',
    },
    strokeOrder: ['M 20,50 L 25,30', 'M 30,50 L 32,30'],
    isBatchim: false,
  },
  {
    char: 'ㅓ',
    name: '어',
    nameRomanized: 'eo',
    romanization: 'eo',
    category: 'vowel',
    sound: '/ʌ/',
    zhTW: {
      description: '這個音在中文和注音中沒有完全對應的。嘴巴微張、自然放鬆，舌頭在口腔中間偏後的位置。類似英文 "up" 的 "u"。',
      mnemonic: '想像你若有所思地發出「呃⋯⋯」的聲音。左邊的長豎象徵嘴巴微張。',
      similar: '介於「哦」和「呃」之間，嘴型比「ㅏ」小',
    },
    strokeOrder: ['M 20,30 L 20,55', 'M 30,30 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅕ',
    name: '여',
    nameRomanized: 'yeo',
    romanization: 'yeo',
    category: 'vowel',
    sound: '/jʌ/',
    zhTW: {
      description: '由「ㅣ」(i) +「ㅓ」(eo) 組合而成。先發出短促的「ㅣ」再快速滑到「ㅓ」。',
      mnemonic: '比「ㅓ」多了一小橫，加上 y 的音。兩橫 = yeo。',
      similar: '先發「y」再發「ㅓ」，一氣呵成',
    },
    strokeOrder: ['M 20,30 L 18,55', 'M 30,30 L 32,55'],
    isBatchim: false,
  },
  {
    char: 'ㅗ',
    name: '오',
    nameRomanized: 'o',
    romanization: 'o',
    category: 'vowel',
    sound: '/o/',
    zhTW: {
      description: '嘴唇圓攏向前突出，舌頭後縮。類似中文「哦」，但韓文的「ㅗ」嘴唇更圓、更高。',
      mnemonic: '像一個圓圈在上方，代表嘴唇圓圓的。上面的短橫是嘴巴形狀。',
      similar: '類似注音「ㄛ」，嘴唇更圓更突出',
    },
    strokeOrder: ['M 25,30 L 25,55'],
    isBatchim: false,
  },
  {
    char: 'ㅛ',
    name: '요',
    nameRomanized: 'yo',
    romanization: 'yo',
    category: 'vowel',
    sound: '/jo/',
    zhTW: {
      description: '由「ㅣ」(i) +「ㅗ」(o) 組合而成。先發出短促的「ㅣ」再快速滑到「ㅗ」。類似中文「唷」。',
      mnemonic: '比「ㅗ」多了兩個小點（小橫），就像「yo」多了一個音節。',
      similar: '類似中文「唷」，嘴型先扁後圓',
    },
    strokeOrder: ['M 25,30 L 25,55'],
    isBatchim: false,
  },
  {
    char: 'ㅜ',
    name: '우',
    nameRomanized: 'u',
    romanization: 'u',
    category: 'vowel',
    sound: '/u/',
    zhTW: {
      description: '嘴唇圓攏向前突出，比「ㅗ」更緊更突出。類似中文「嗚」，但韓文的「ㅜ」嘴唇更用力。',
      mnemonic: '下面的長橫像嘴巴用力嘟起來。想像要吹蠟燭的嘴型。',
      similar: '類似注音「ㄨ」，嘴唇更用力突出',
    },
    strokeOrder: ['M 25,50 L 25,75'],
    isBatchim: false,
  },
  {
    char: 'ㅠ',
    name: '유',
    nameRomanized: 'yu',
    romanization: 'yu',
    category: 'vowel',
    sound: '/ju/',
    zhTW: {
      description: '由「ㅣ」(i) +「ㅜ」(u) 組合而成。先發出短促的「ㅣ」再快速滑到「ㅜ」。類似中文「淤」。',
      mnemonic: '比「ㅜ」多了個小點，就像 yu 多了 y。兩個點 = yu。',
      similar: '類似注音「ㄩ」但嘴唇不用那麼扁平',
    },
    strokeOrder: ['M 25,50 L 25,75'],
    isBatchim: false,
  },
  {
    char: 'ㅡ',
    name: '으',
    nameRomanized: 'eu',
    romanization: 'eu',
    category: 'vowel',
    sound: '/ɯ/',
    zhTW: {
      description: '這是最難的韓文母音之一！嘴唇完全不圓、向兩側拉開呈扁平狀，舌頭後縮抬高。類似注音「ㄜ」但舌頭位置更高，或英文 "good" 去掉圓唇。',
      mnemonic: '一條橫線，代表嘴唇扁平拉開。想像假笑的嘴型。',
      similar: '類似注音「ㄜ」但不圓唇，舌根抬高',
    },
    strokeOrder: ['M 15,45 L 40,45'],
    isBatchim: false,
  },
  {
    char: 'ㅣ',
    name: '이',
    nameRomanized: 'i',
    romanization: 'i',
    category: 'vowel',
    sound: '/i/',
    zhTW: {
      description: '嘴唇向兩側拉開，舌尖抵住下齒。類似中文「衣」，非常直觀。',
      mnemonic: '像一根直立的手指，代表「一」。也像數字 1 的發音。',
      similar: '與注音「ㄧ」幾乎相同',
    },
    strokeOrder: ['M 28,20 L 28,60'],
    isBatchim: false,
  },
];

export const basicConsonants: HangulChar[] = [
  {
    char: 'ㄱ',
    name: '기역',
    nameRomanized: 'giyeok',
    romanization: 'g/k',
    category: 'consonant',
    sound: '/k/ → /g/',
    zhTW: {
      description: '在音節開頭讀 [k]（類似「ㄎ」），在兩個母音之間會濁化為 [g]（類似「ㄍ」）。舌根抵住軟顎，用力彈開。',
      mnemonic: '形狀像一把刀的側面（刀 = 칼 kal）。ㄱ 就像刀柄的彎角。',
      similar: '類似「ㄍ」和「ㄎ」之間，開頭送氣較輕',
    },
    strokeOrder: ['M 40,25 L 20,25 L 20,50'],
    isBatchim: true,
    batchimSound: 'k̚（不爆破的 k）',
  },
  {
    char: 'ㄴ',
    name: '니은',
    nameRomanized: 'nieun',
    romanization: 'n',
    category: 'consonant',
    sound: '/n/',
    zhTW: {
      description: '舌尖抵住上齒齦，氣流從鼻腔出來。和中文的「ㄋ」幾乎一樣。',
      mnemonic: '像一個鼻子（nose）的側面輪廓。ㄴ = n = nose。',
      similar: '與注音「ㄋ」幾乎相同',
    },
    strokeOrder: ['M 20,25 L 20,55 L 45,55'],
    isBatchim: true,
    batchimSound: 'n',
  },
  {
    char: 'ㄷ',
    name: '디귿',
    nameRomanized: 'digeut',
    romanization: 'd/t',
    category: 'consonant',
    sound: '/t/ → /d/',
    zhTW: {
      description: '在音節開頭讀 [t]（類似「ㄊ」但送氣較少），在母音之間濁化為 [d]（類似「ㄉ」）。舌尖抵住上齒齦。',
      mnemonic: '像一扇門（door）的形狀。ㄷ = d = door。',
      similar: '類似「ㄉ」和「ㄊ」之間，比中文的 d 更輕',
    },
    strokeOrder: ['M 25,25 L 45,25 L 35,45'],
    isBatchim: true,
    batchimSound: 't̚（不爆破的 t）',
  },
  {
    char: 'ㄹ',
    name: '리을',
    nameRomanized: 'rieul',
    romanization: 'r/l',
    category: 'consonant',
    sound: '/ɾ/ ~ /l/',
    zhTW: {
      description: '在音節開頭類似日文的ら行彈舌音 [ɾ]，舌尖快速輕拍上齒齦一下。在音節尾或連續兩個ㄹ時讀 [l]。注意：和中文的「ㄌ」不太一樣！',
      mnemonic: '像藤蔓纏繞，彎彎曲曲的。ㄹ 彎了三次。',
      similar: '類似日文「ら」的彈舌音，比中文「ㄌ」更輕快',
    },
    strokeOrder: ['M 20,25 L 40,30 L 25,40 L 45,45 L 30,55'],
    isBatchim: true,
    batchimSound: 'l',
  },
  {
    char: 'ㅁ',
    name: '미음',
    nameRomanized: 'mieum',
    romanization: 'm',
    category: 'consonant',
    sound: '/m/',
    zhTW: {
      description: '雙唇閉合，氣流從鼻腔出來。和中文的「ㄇ」一樣。',
      mnemonic: '像一個嘴巴（mouth）的口形。ㅁ = m = mouth。',
      similar: '與注音「ㄇ」相同',
    },
    strokeOrder: ['M 20,25 L 20,55 M 40,25 L 40,55 M 20,25 L 40,25 M 20,55 L 40,55'],
    isBatchim: true,
    batchimSound: 'm',
  },
  {
    char: 'ㅂ',
    name: '비읍',
    nameRomanized: 'bieup',
    romanization: 'b/p',
    category: 'consonant',
    sound: '/p/ → /b/',
    zhTW: {
      description: '在音節開頭讀 [p]（類似「ㄆ」但送氣較少），在母音之間濁化為 [b]（類似「ㄅ」）。雙唇先閉合再爆開。',
      mnemonic: '像一個杯子（bucket/bottle）的形狀。ㅂ = b = bottle。',
      similar: '類似「ㄅ」和「ㄆ」之間，注意不要用力送氣',
    },
    strokeOrder: ['M 20,25 L 20,55 M 40,25 L 40,55 M 20,35 L 40,35'],
    isBatchim: true,
    batchimSound: 'p̚（不爆破的 p）',
  },
  {
    char: 'ㅅ',
    name: '시옷',
    nameRomanized: 'siot',
    romanization: 's',
    category: 'consonant',
    sound: '/s/ ~ /ɕ/',
    zhTW: {
      description: '在「ㅣ、ㅑ、ㅕ、ㅛ、ㅠ、ㅟ」等前讀 [ɕ]（類似「ㄒ」），其他情況讀 [s]（類似「ㄙ」）。氣流從舌尖和齒縫間摩擦而出。',
      mnemonic: '像一個人在微笑（smile），嘴角上揚。ㅅ = s = smile。',
      similar: '類似「ㄙ」，但接 i 系列母音時更像「ㄒ」',
    },
    strokeOrder: ['M 40,25 L 20,40 L 40,55'],
    isBatchim: true,
    batchimSound: 't̚（注意！終聲ㅅ讀 t）',
  },
  {
    char: 'ㅇ',
    name: '이응',
    nameRomanized: 'ieung',
    romanization: '(無聲) / ng',
    category: 'consonant',
    sound: '字首無聲 / 字尾 ŋ',
    zhTW: {
      description: '在音節開頭不發音（零聲母），只是一個佔位符號。在音節結尾讀 [ŋ]（類似「ㄥ」）。是韓文中唯一有兩種完全不同功能的字母。',
      mnemonic: '像數字 0，代表沒有聲音（zero sound）。在結尾時像喉嚨深處發出的「嗯——」。',
      similar: '字首不發音，字尾類似「ㄥ」',
    },
    strokeOrder: ['M 30,25 C 42,25 45,35 45,42 C 45,48 42,55 30,55 C 18,55 15,48 15,42 C 15,35 18,25 30,25 Z'],
    isBatchim: true,
    batchimSound: 'ŋ（ng）',
  },
  {
    char: 'ㅈ',
    name: '지읒',
    nameRomanized: 'jieut',
    romanization: 'j',
    category: 'consonant',
    sound: '/tɕ/ → /dʑ/',
    zhTW: {
      description: '在音節開頭讀 [tɕ]（類似「ㄐ」但送氣較少），在母音之間濁化為 [dʑ]。舌尖抵住下齒，舌面貼上硬顎。',
      mnemonic: '像一個人在鞠躬（절 = 鞠躬），ㅈ 就像彎腰的形狀。',
      similar: '類似「ㄐ」，但比中文的 j 發音位置更靠前',
    },
    strokeOrder: ['M 25,25 L 25,55 M 25,30 L 45,30 M 25,40 L 45,40'],
    isBatchim: true,
    batchimSound: 't̚（注意！終聲ㅈ讀 t）',
  },
  {
    char: 'ㅊ',
    name: '치읓',
    nameRomanized: 'chieut',
    romanization: 'ch',
    category: 'consonant',
    sound: '/tɕʰ/',
    zhTW: {
      description: '和「ㅈ」的發音位置相同，但要用力送氣。類似中文「ㄑ」。ㅈ 上面加一小橫表示送氣。',
      mnemonic: '比「ㅈ」多了一小橫在上方 = 多了一口氣 = 送氣音。',
      similar: '類似「ㄑ」，送氣明顯',
    },
    strokeOrder: ['M 25,22 L 45,22 M 25,25 L 25,55 M 25,33 L 45,33 M 25,43 L 45,43'],
    isBatchim: true,
    batchimSound: 't̚（終聲讀 t）',
  },
  {
    char: 'ㅋ',
    name: '키읔',
    nameRomanized: 'kieuk',
    romanization: 'k',
    category: 'consonant',
    sound: '/kʰ/',
    zhTW: {
      description: '和「ㄱ」的發音位置相同，但要用力送氣。類似中文「ㄎ」。ㄱ 中間加一橫表示送氣加強。',
      mnemonic: 'ㄱ + 中間一橫 = 加氣版 ㄱ。像卡車（卡 = 카）的 k。',
      similar: '類似「ㄎ」，送氣很強',
    },
    strokeOrder: ['M 20,35 L 40,35 M 20,25 L 20,50'],
    isBatchim: true,
    batchimSound: 'k̚',
  },
  {
    char: 'ㅌ',
    name: '티읕',
    nameRomanized: 'tieut',
    romanization: 't',
    category: 'consonant',
    sound: '/tʰ/',
    zhTW: {
      description: '和「ㄷ」的發音位置相同，但要用力送氣。類似中文「ㄊ」。ㄷ 多加了一橫。',
      mnemonic: 'ㄷ + 多一橫 = 加氣版 ㄷ。像踢球（踢 = 與 발차기 無關但記 t）。',
      similar: '類似「ㄊ」，送氣很強',
    },
    strokeOrder: ['M 25,25 L 45,25 M 20,30 L 35,45 M 20,50 L 35,35'],
    isBatchim: true,
    batchimSound: 't̚',
  },
  {
    char: 'ㅍ',
    name: '피읖',
    nameRomanized: 'pieup',
    romanization: 'p',
    category: 'consonant',
    sound: '/pʰ/',
    zhTW: {
      description: '和「ㅂ」的發音位置相同，但要用力送氣。類似中文「ㄆ」。像ㅠ 但上面是平的。',
      mnemonic: 'ㅂ 的變形版，上面橫線代表示送氣。想像吹氣（puff）的 p。',
      similar: '類似「ㄆ」，送氣很強',
    },
    strokeOrder: ['M 20,25 L 40,25 M 20,25 L 20,55 M 35,25 L 35,55 M 20,35 L 35,35'],
    isBatchim: true,
    batchimSound: 'p̚',
  },
  {
    char: 'ㅎ',
    name: '히읗',
    nameRomanized: 'hieut',
    romanization: 'h',
    category: 'consonant',
    sound: '/h/',
    zhTW: {
      description: '類似中文「ㄏ」，從喉嚨深處輕輕送氣。注意：韓文的「ㅎ」比中文的 h 更輕柔，有時在母音之間幾乎不發音。',
      mnemonic: '像一頂帽子（hat）戴在頭上。上面的小圓圈像帽頂。',
      similar: '類似「ㄏ」但更輕柔',
    },
    strokeOrder: ['M 30,22 C 38,22 42,25 42,28 M 20,28 L 42,28 M 20,50 L 42,50 M 20,50 L 20,28 M 42,50 L 42,28'],
    isBatchim: true,
    batchimSound: 't̚（注意！終聲ㅎ讀 t）',
  },
];

export const compoundVowels: HangulChar[] = [
  {
    char: 'ㅐ',
    name: '애',
    nameRomanized: 'ae',
    romanization: 'ae',
    category: 'compound-vowel',
    sound: '/ɛ/',
    zhTW: { description: '由「ㅏ」(a) +「ㅣ」(i) 組成。嘴型比「ㅏ」稍扁，類似英文 "bed" 的 "e"。', mnemonic: 'ㅏ + ㅣ = ㅐ。比 ㅏ 多了個 i 的味道，嘴型微扁。', similar: '類似英文 "bed" 的 e' },
    strokeOrder: ['M 15,30 L 20,30 M 15,50 L 25,50 M 30,20 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅒ',
    name: '얘',
    nameRomanized: 'yae',
    romanization: 'yae',
    category: 'compound-vowel',
    sound: '/jɛ/',
    zhTW: { description: '由「ㅑ」(ya) +「ㅣ」(i) 組成。先發 y 再滑到 ㅐ。', mnemonic: 'ㅑ + ㅣ = ㅒ。雙倍 i，雙倍 y。', similar: '類似「耶」，但嘴型更開' },
    strokeOrder: ['M 15,30 L 18,30 M 15,50 L 25,50 M 30,20 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅔ',
    name: '에',
    nameRomanized: 'e',
    romanization: 'e',
    category: 'compound-vowel',
    sound: '/e/',
    zhTW: { description: '由「ㅓ」(eo) +「ㅣ」(i) 組成。嘴型比「ㅓ」稍扁稍高。類似英文 "egg" 的 "e"。', mnemonic: 'ㅓ + ㅣ = ㅔ。在 ㅓ 的基礎上加 i 的味道。', similar: '類似英文 "egg" 的 e' },
    strokeOrder: ['M 15,30 L 15,55 M 30,20 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅖ',
    name: '예',
    nameRomanized: 'ye',
    romanization: 'ye',
    category: 'compound-vowel',
    sound: '/je/',
    zhTW: { description: '由「ㅕ」(yeo) +「ㅣ」(i) 組成。先發 y 再滑到 ㅔ。注意：現代韓語中 ㅖ 和 ㅒ 的發音已趨近相同。', mnemonic: 'ㅕ + ㅣ = ㅖ。雙 i，雙 y。', similar: '類似「耶」，現代韓語中與 ㅒ 幾乎相同' },
    strokeOrder: ['M 15,30 L 12,55 M 30,20 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅘ',
    name: '와',
    nameRomanized: 'wa',
    romanization: 'wa',
    category: 'compound-vowel',
    sound: '/wa/',
    zhTW: { description: '由「ㅗ」(o) +「ㅏ」(a) 組成。先圓唇發 ㅗ 再快速滑到 ㅏ。類似中文「哇」。', mnemonic: 'ㅗ + ㅏ = ㅘ。圓嘴變大嘴 = wa！', similar: '類似中文「哇」' },
    strokeOrder: ['M 20,30 L 20,50 M 30,30 L 30,50'],
    isBatchim: false,
  },
  {
    char: 'ㅙ',
    name: '왜',
    nameRomanized: 'wae',
    romanization: 'wae',
    category: 'compound-vowel',
    sound: '/wɛ/',
    zhTW: { description: '由「ㅗ」(o) +「ㅐ」(ae) 組成。先圓唇發 ㅗ 再快速滑到 ㅐ。類似中文「歪」。', mnemonic: 'ㅗ + ㅐ = ㅙ。圓嘴變扁嘴 = wae！', similar: '類似中文「歪」' },
    strokeOrder: ['M 20,30 L 20,50 M 25,30 L 28,30 M 25,50 L 32,50 M 40,20 L 40,55'],
    isBatchim: false,
  },
  {
    char: 'ㅚ',
    name: '외',
    nameRomanized: 'oe',
    romanization: 'oe',
    category: 'compound-vowel',
    sound: '/ø/ ~ /we/',
    zhTW: { description: '原本是單母音 /ø/（圓唇發 ㅔ），現代首爾口語中常讀成 [we]。由「ㅗ」(o) +「ㅣ」(i) 組成。', mnemonic: 'ㅗ + ㅣ = ㅚ。圓嘴加微笑 = oe/we。', similar: '傳統讀法似德文 ö，現代常讀似 "we"' },
    strokeOrder: ['M 20,30 L 20,50 M 40,20 L 40,55'],
    isBatchim: false,
  },
  {
    char: 'ㅝ',
    name: '워',
    nameRomanized: 'wo',
    romanization: 'wo',
    category: 'compound-vowel',
    sound: '/wʌ/',
    zhTW: { description: '由「ㅜ」(u) +「ㅓ」(eo) 組成。先圓唇發 ㅜ 再快速滑到 ㅓ。類似中文「我」去掉尾音。', mnemonic: 'ㅜ + ㅓ = ㅝ。嘟嘴變半開 = wo！', similar: '類似 "watch" 的 wa 但口型較小' },
    strokeOrder: ['M 20,50 L 20,70 M 30,30 L 30,55'],
    isBatchim: false,
  },
  {
    char: 'ㅞ',
    name: '웨',
    nameRomanized: 'we',
    romanization: 'we',
    category: 'compound-vowel',
    sound: '/we/',
    zhTW: { description: '由「ㅜ」(u) +「ㅔ」(e) 組成。先圓唇發 ㅜ 再快速滑到 ㅔ。類似英文 "wet"。', mnemonic: 'ㅜ + ㅔ = ㅞ。嘟嘴加小口 = we！', similar: '類似英文 "wet" 的 we' },
    strokeOrder: ['M 20,50 L 20,70 M 30,30 L 30,55 M 42,20 L 42,55'],
    isBatchim: false,
  },
  {
    char: 'ㅟ',
    name: '위',
    nameRomanized: 'wi',
    romanization: 'wi',
    category: 'compound-vowel',
    sound: '/y/ ~ /wi/',
    zhTW: { description: '由「ㅜ」(u) +「ㅣ」(i) 組成。傳統讀 /y/（圓唇發 i），現代常讀 [wi]。類似英文 "we"。', mnemonic: 'ㅜ + ㅣ = ㅟ。嘟嘴微笑 = wi！', similar: '類似英文 "we"' },
    strokeOrder: ['M 20,50 L 20,70 M 40,20 L 40,55'],
    isBatchim: false,
  },
  {
    char: 'ㅢ',
    name: '의',
    nameRomanized: 'ui',
    romanization: 'ui',
    category: 'compound-vowel',
    sound: '/ɰi/',
    zhTW: { description: '由「ㅡ」(eu) +「ㅣ」(i) 組成。先發 ㅡ 再快速滑到 ㅣ。在所有複合母音中最難！注意：作所有格助詞時讀 [e]。', mnemonic: 'ㅡ + ㅣ = ㅢ。扁嘴變微笑 = ui！', similar: '快速連讀 eu + i，類似「呃伊」快速念' },
    strokeOrder: ['M 15,45 L 40,45 M 40,20 L 40,55'],
    isBatchim: false,
  },
];

export const doubleConsonants: HangulChar[] = [
  {
    char: 'ㄲ',
    name: '쌍기역',
    nameRomanized: 'ssanggiyeok',
    romanization: 'kk',
    category: 'double-consonant',
    sound: '/k͈/',
    zhTW: { description: '「ㄱ」的緊音版。喉嚨用力收緊，不送氣，發出來比 ㄱ 更硬更緊。', mnemonic: '兩個 ㄱ = 雙倍用力 = 喉嚨鎖緊的 k！', similar: '像憋著氣發「ㄍ」，非常緊繃' },
    strokeOrder: ['M 20,25 L 20,50 M 30,25 L 30,50 M 40,25 L 40,50'],
    isBatchim: true,
    batchimSound: 'k̚（緊音）',
  },
  {
    char: 'ㄸ',
    name: '쌍디귿',
    nameRomanized: 'ssangdigeut',
    romanization: 'tt',
    category: 'double-consonant',
    sound: '/t͈/',
    zhTW: { description: '「ㄷ」的緊音版。舌頭用力頂住上顎，不送氣。類似中文「ㄉ」但更用力。', mnemonic: '兩個 ㄷ = 舌頭用力頂！像憋著氣發「ㄉ」。', similar: '像憋著氣發「ㄉ」，舌頭非常用力' },
    strokeOrder: ['M 15,25 L 35,25 L 30,45 M 30,25 L 50,25 L 45,45'],
    isBatchim: false,
  },
  {
    char: 'ㅃ',
    name: '쌍비읍',
    nameRomanized: 'ssangbieup',
    romanization: 'pp',
    category: 'double-consonant',
    sound: '/p͈/',
    zhTW: { description: '「ㅂ」的緊音版。雙唇用力閉緊再爆開，不送氣。', mnemonic: '兩個 ㅂ = 嘴唇用力！像憋著氣發「ㄅ」。', similar: '像憋著氣發「ㄅ」，嘴唇非常緊繃' },
    strokeOrder: ['M 15,25 L 15,55 M 25,25 L 25,55 M 15,35 L 25,35 M 35,25 L 35,55 M 45,25 L 45,55 M 35,35 L 45,35'],
    isBatchim: false,
  },
  {
    char: 'ㅆ',
    name: '쌍시옷',
    nameRomanized: 'ssangsiot',
    romanization: 'ss',
    category: 'double-consonant',
    sound: '/s͈/',
    zhTW: { description: '「ㅅ」的緊音版。氣流更集中、摩擦更強。類似中文「ㄙ」但更用力。', mnemonic: '兩個 ㅅ = 雙倍摩擦！像蛇吐信的聲音但更用力。', similar: '比「ㄙ」更用力更尖銳' },
    strokeOrder: ['M 20,25 L 12,40 L 20,55 M 35,25 L 27,40 L 35,55'],
    isBatchim: true,
    batchimSound: 't̚',
  },
  {
    char: 'ㅉ',
    name: '쌍지읒',
    nameRomanized: 'ssangjieut',
    romanization: 'jj',
    category: 'double-consonant',
    sound: '/t͈ɕ/',
    zhTW: { description: '「ㅈ」的緊音版。舌面用力貼緊硬顎，不送氣。類似中文「ㄐ」但更用力。', mnemonic: '兩個 ㅈ = 舌頭用力貼！像憋著氣發「ㄐ」。', similar: '像憋著氣發「ㄐ」，舌頭非常用力' },
    strokeOrder: ['M 15,25 L 15,55 M 15,30 L 30,30 M 15,40 L 30,40 M 35,25 L 35,55 M 35,30 L 50,30 M 35,40 L 50,40'],
    isBatchim: false,
  },
];

// 所有字母的統一陣列
export const allHangulChars: HangulChar[] = [
  ...basicVowels,
  ...basicConsonants,
  ...compoundVowels,
  ...doubleConsonants,
];

// 依類別取得字母
export function getCharsByCategory(category: HangulChar['category']): HangulChar[] {
  return allHangulChars.filter(c => c.category === category);
}

// 取得可做終聲的字母
export function getBatchimChars(): HangulChar[] {
  return allHangulChars.filter(c => c.isBatchim);
}
